name: p2 - Condition

on: workflow_dispatch

jobs:
  build:
    runs-on: self-hosted
    if: ${{ github.event_name == 'workflow_dispatch' && github.ref == 'refs/heads/dev' }}
    steps:
      - name: hi
        run: |
          echo "hi $GITHUB_ACTOR"
