name: p3 - Env

on: workflow_dispatch

jobs:
  step_get_set_env:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - id: generate-random-id
        name: Generate random string
        run: echo "random_id=$RANDOM" >> "$GITHUB_OUTPUT"
      - id: build-project
        name: Build project
        run: |
          echo "Random ID: ${{ steps.generate-random-id.outputs.random_id }}"
      - id: run-tests
        name: Run tests
        run: |
          echo "Random ID: ${{ steps.generate-random-id.outputs.random_id }}"
  job_set_env:
    name: Set ENV
    runs-on: self-hosted
    outputs:
      output1: ${{ steps.build_project.outputs.build_id }}
      output2: ${{ steps.test_project.outputs.test_output }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: build_project
        run: |
          echo "build_id=$GITHUB_JOB"
          echo "build_id=$GITHUB_JOB" >> "$GITHUB_OUTPUT"
      - name: test_project
        run: |
          echo "test_output=pass"
          echo "test_output=pass" >> "$GITHUB_OUTPUT"
  job_get_env:
    name: Get ENV
    needs: job_set_env
    runs-on: [self-hosted]
    steps:
      - name: Check
        env:
          build_id: ${{ needs.job_set_env.outputs.output1 }}
          test_output: ${{ needs.job_set_env.outputs.output2 }}
        run: |
          echo "Build ID: ${{ env.build_id }}"
          echo "Test Output: ${{ env.test_output }}"
      - name: Deploy to production
        env:
          test_output: ${{ needs.job_set_env.outputs.output2 }}
        if: ${{ env.test_output == 'pass' }}
        run: |
          echo "Build ID: $build_id"
          echo "Deploying to production server"
