name: p9 - Secret
on: workflow_dispatch
jobs:
  vars:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get variables
        run: |
          echo "variable : ${{ vars.TEST_VAR }}"
          echo "secret : ${{ secrets.TEST_SECRET }}"